### ISSUE TITLE
Разобраться с curl

### ISSUE THREAD

**Issue by dolgihnatasha** [urfu-2015/team4#11]
curl -d "name=test&email=test@test.ru&password=test" http://localhost:3000/user/reg

**Comment by dolgihnatasha** [comment]
https://curl.haxx.se/docs/manual.html

**Comment by dolgihnatasha** [comment]
консолька зависает при вызове 
`curl -d "name=test&email=test@test.ru&password=test" http://localhost:3000/user/reg`
хотя вроде все должно быть нормально
может это проблема на сервере?

**Comment by NekrasovAlexey** [comment]
Ты пробуешь уже на исправленных файлах?

**Comment by dolgihnatasha** [comment]
нет еще, надо бы попробовать
когда я последний раз его запускала, оно не висло
может что-то с того момента фиксили

**Comment by NekrasovAlexey** [comment]
В любом случае, если висит PR с исправлениями, значит на данный момент что-то сделано не так

**Comment by NekrasovAlexey** [comment]
Еще внесут кое-какие правки и тогда будет работать
