### ISSUE TITLE
разобраться Yandex Карты API

### ISSUE THREAD

**Issue by patrn1** [urfu-2015/team4#59]

**Comment by v-samoylov** [comment]
https://github.com/v-samoylov/YandexMapsPage
Метки по клику + метки по адресу

**Comment by v-samoylov** [comment]
пока токо города находит

**Comment by v-samoylov** [comment]
не все улицы находятся правильно

**Comment by patrn1** [comment]
- указание места на карте по клику. ставится метка
- удаление метки двумя кликами по ней
- указание места на карте по адресу (метка ставится на самый релевантный к запросу результат)
- при наведении на метку показывается подсказка с адресом, на который она поставлена

https://github.com/v-samoylov/YandexMapsPage
